# Generated by Django 6.0.7 on 2026-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditjob',
            name='progress_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditjob',
            name='device_type',
            field=models.CharField(choices=[('cbw', 'CBW'), ('tf_vnc', 'TF VNC'), ('pole_bundle', 'Pole capture (CBW + VNC L1/L2)')], max_length=16),
        ),
    ]
