# Generated by Django 6.0.7 on 2026-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditjob_progress_message_alter_auditjob_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditjob',
            name='device_type',
            field=models.CharField(choices=[('cbw', 'CBW'), ('tf_vnc', 'TF VNC'), ('pole_bundle', 'Pole capture (CBW + VNC L1/L2)'), ('de_tv', 'DragonEye TeamViewer'), ('de_bundle', 'DragonEye capture (TeamViewer lanes)')], max_length=16),
        ),
    ]
