# Generated by Django 6.0.7 on 2026-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(db_index=True, max_length=128, unique=True)),
                ('fl_number', models.CharField(blank=True, max_length=64)),
                ('pole_number', models.CharField(db_index=True, max_length=64)),
                ('state', models.CharField(blank=True, db_index=True, max_length=64)),
                ('agency', models.CharField(blank=True, db_index=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('assigned', models.CharField(blank=True, max_length=128)),
                ('lane_group', models.CharField(blank=True, max_length=64)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('model_type', models.CharField(blank=True, max_length=128)),
                ('certification_expiry', models.CharField(blank=True, max_length=64)),
                ('lane_direction', models.CharField(blank=True, max_length=64)),
                ('last_report', models.CharField(blank=True, max_length=128)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('tier_by_value', models.FloatField(blank=True, null=True)),
                ('daily_revenue', models.FloatField(blank=True, null=True)),
                ('school_start_date', models.CharField(blank=True, max_length=64)),
                ('address_audit_status', models.CharField(blank=True, max_length=128)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('modem_ip_address', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pole_number', 'serial'],
            },
        ),
    ]
