# Generated by Django 6.0.7 on 2026-07-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ims_id', models.IntegerField(db_index=True, unique=True)),
                ('identifier', models.CharField(blank=True, db_index=True, max_length=128)),
                ('primary_platform', models.CharField(blank=True, db_index=True, max_length=64)),
                ('all_platforms', models.CharField(blank=True, max_length=255)),
                ('pole_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('fl_number', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, db_index=True, max_length=64)),
                ('agency', models.CharField(blank=True, db_index=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, db_index=True, max_length=64)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('ims_updated_at', models.CharField(blank=True, max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['pole_number', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ims_role', models.CharField(blank=True, default='readonly', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
