# Generated by Django 6.0.7 on 2026-07-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_installation_syncstate_userprofile_delete_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('host', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cameras.installation')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ims_device_id', models.IntegerField(db_index=True)),
                ('enclosure_id', models.IntegerField(default=0)),
                ('enclosure_label', models.CharField(blank=True, max_length=255)),
                ('lane_code', models.CharField(blank=True, max_length=32)),
                ('unit_serial', models.CharField(blank=True, max_length=128)),
                ('prtg_objid', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('host', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device_type', models.CharField(blank=True, max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='cameras.installation')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prtg_objid', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('last_value', models.CharField(blank=True, max_length=255)),
                ('sensor_type', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='cameras.installationdevice')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='installationdevice',
            constraint=models.UniqueConstraint(fields=('installation', 'ims_device_id'), name='uniq_installation_ims_device'),
        ),
    ]
