# Generated by Django 6.0.7 on 2026-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_installationcomponent_installationdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='camera_a',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='installation',
            name='camera_b',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='installation',
            name='camera_c',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='installation',
            name='tf_a_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='installation',
            name='tf_b_ip',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
