# Generated by Django 6.0.7 on 2026-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_installation_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragonEyeTeamViewerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fx_number', models.CharField(db_index=True, max_length=32)),
                ('lane', models.CharField(blank=True, default='', max_length=8)),
                ('teamviewer_id', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fx_number', 'lane'],
                'constraints': [models.UniqueConstraint(fields=('fx_number', 'lane'), name='uniq_dragoneye_fx_lane')],
            },
        ),
    ]
